version: '3.8'

services:
  sqlmap-api:
    build: .
    container_name: sqlmap-api
    ports:
      - "8775:8775"
    volumes:
      - ./data:/app/data

  sqlmap-proxy:
    build: node-api
    container_name: sqlmap-proxy
    ports:
      - "8776:8776"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SQLMAP_API_URL=http://sqlmap-api:8775
      - CORS_ORIGIN=*
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
